#
# Umber Common Database.

parameters:
  umber.database.paginator.page.default: 1
  umber.database.paginator.limit.default: 25

services:

  umber.database.paginator.factory:
    class: 'Umber\Database\Pagination\PaginatorFactory'
    arguments:
      - '@request_stack'
      - '%umber.database.paginator.page.default%'
      - '%umber.database.paginator.limit.default%'

  umber.database.manager.doctrine:
    class: 'Umber\Database\Manager\DoctrineDatabaseManager'
    arguments:
      - '@doctrine'
