#
# Umber Reducer.

services:

  umber.reducer.registry:
    class: 'Umber\Reducer\Registry\ReducerHandlerRegistry'

  umber.reducer.type.resolver:
    class: 'Umber\Reducer\Type\Resolver\TypeResolver'

  umber.reducer:
    class: 'Umber\Reducer\Reducer'
    arguments:
      - '@umber.reducer.type.resolver'

  umber.reducer.factory:
    class: 'Umber\Reducer\Factory\ReducerFactory'
    arguments:
      - '@umber.reducer.type.resolver'
      - '@umber.reducer.registry'

  umber.reducer.builder:
    class: 'Umber\Reducer\Builder\ReducerBuilderFactory'
    arguments:
      - '@umber.reducer.factory'
      - '@umber.reducer.factory.context'

  umber.reducer.factory.context:
    class: 'Umber\Reducer\Factory\ReducerContextFactory'
