#
# Umber Common Serializer.

services:

  umber.common.serializer:
    class: 'Umber\Common\Serializer\Serializer'
    arguments:
      - '@?jms_serializer.serializer'
    public: false

  umber.common.serializer.reducer:
    class: 'Umber\Common\Serializer\ReducerSerializer'
    arguments:
      - '@umber.common.reducer.builder'
